name: Feature Request
description: Suggest an idea for this project
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Feature Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and consise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered.
      placeholder: A clear and consise description of any alternative solutions or features that you've considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
